### PR TITLE
Install gcc 4.8 on SUSE < 12

### PR DESCRIPTION
**Pull request by scotthain**
### Description

This allows builds of Ruby on SLES/SUSE 11.4 to succeed.

### Issues Resolved

[List any existing issues this PR resolves]

### Check List
- [x] All tests pass. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] The CLA has been signed. See https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD

Signed-off-by: Scott Hain <shain@chef.io>

### CODE REVIEW

**Comment by scotthain** [comment]
@chef-cookbooks/engineering-services

**Comment by tas50** [comment]
Do we support Suse < 12?

**Comment by scotthain** [comment]
@tas50 sles is treated as suse, and we support sles 11.4

**Comment by tas50** [comment]
I didn't realize we supported SLES 11.

**Pull request merged**
