### PR TITLE
Ensure kernel-devel matches the running kernel

### PR DESCRIPTION
**Pull request by imduffy15**
Force the version of kernel-devel that is installed to match that of
the running kernel.

Signed-off-by: Ian Duffy <ian@ianduffy.ie>

### CODE REVIEW

**Comment by imduffy15** [comment]
That build failure is totally unrelated to the proposed changes.

**Comment by samdunne** [comment]
+1

**Comment by imduffy15** [comment]
Any update on this?

**Comment by schisamo** [comment]
:+1: 

/cc @chef-cookbooks/engineering-services

**Comment by scotthain** [comment]
:+1:

**Comment by schisamo** [comment]
@imduffy15 Let's add some ChefSpec coverage for this change and squash things down into one commit and we'll get this merged.

**Comment by imduffy15** [comment]
Sorry for the delay! Updated as requested @schisamo Will see how the travis run goes :)

**Pull request merged**
