### PR TITLE
Prepare 2.3.0 release

### PR DESCRIPTION
**Pull request by jaym**
cc @chef-cookbooks/engineering-services

### CODE REVIEW

**Comment by scotthain** [comment]
@jaym looks like some test failures?

**Comment by jaym** [comment]
yea, the foodcritic tests have never passed. Maybe @tas50 knows how to fix them

**Comment by tas50** [comment]
There's a rubocop error that's super simple to fix.  The libraries need some work though.  They have bad action methods and aren't using use_inline_resources.  That should probably get fixed up.

**Comment by jaym** [comment]
@tas50 i tried that and then it ended up complaining about something else

**Comment by jaym** [comment]
```diff
diff --git i/libraries/xcode_command_line_tools.rb w/libraries/xcode_command_line_tools.rb
index 216b7df..5061bad 100644
--- i/libraries/xcode_command_line_tools.rb
+++ w/libraries/xcode_command_line_tools.rb
@@ -60,7 +60,9 @@ end
 #
 class Chef
   class Provider::XcodeCommandLineToolsFromDmg < Provider::LWRPBase
-    action(:install) do
+    use_inline_resources
+
+    action :install do
       if installed?
         Chef::Log.debug("#{new_resource} already installed - skipping")
       else
@@ -168,7 +170,9 @@ end

 class Chef
   class Provider::XcodeCommandLineToolsFromSoftwareUpdate < Provider::LWRPBase
-    action(:install) do
+    use_inline_resources
+
+    action :install do
       if installed?
         Chef::Log.debug("#{new_resource} already installed - skipping")
       else
```
```

jmundrawala@seamundrawala01 ~/workspace/build-essential (jdm/2.3.0●)$ bundle exec rake style     [2.1.2]
Starting Foodcritic linting...
FC023: Prefer conditional attributes: /Users/jmundrawala/workspace/build-essential/providers/msys_archive.rb:29
FC058: Library provider declares use_inline_resources and declares #action_<name> methods: /Users/jmundrawala/workspace/build-essential/libraries/xcode_command_line_tools.rb:62
FC058: Library provider declares use_inline_resources and declares #action_<name> methods: /Users/jmundrawala/workspace/build-essential/libraries/xcode_command_line_tools.rb:172
jmundrawala@seamundrawala01 ~/workspace/build-essential (jdm/2.3.0●)$
```

**Comment by ksubrama** [comment]
:+1:

**Comment by tas50** [comment]
@jaym Chat with lamont about that rule.  It's his and I haven't had the joy of cleaning them up yet.

**Pull request merged**
