### PR TITLE
Update gcc version for newer omnios versions.

### PR DESCRIPTION
**Pull request by nhuff**
I included a test for 151014 since it is the latest LTS release, but
looking at the release notes the version of gcc actually changed in
151008 so that is what I had the recipe test.

### CODE REVIEW

**Comment by nhuff** [comment]
I think the build failure is do to fauxhai not being able to download the latest system definitions while being run inside travis.

**Comment by cstewart87** [comment]
I'm having a similar error running some local builds.  Is there a solution/workaround for the fauxhai failure?

**Comment by tas50** [comment]
Fauxhai has been updated so it should be shipping with the latest and greatest defs now.  Can you rebase this and we can see if we can get the tests passing.

**Comment by nhuff** [comment]
Rebased and it looks like the tests are passing now.

**Comment by tas50** [comment]
Thanks for getting that fixed up

**Pull request merged**
